version: 0.4.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: E99wzSj/QRlkbtz5uJmK1C8hnDkLCXhPONRMZqiNLRqUotTvaKNgqJETE3BZPVt8bcm1myyccLg4qD4RwRPxWDF2GVFznIS+OPn58h7t42s=