version: 0.4.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 0E2m/8I0e2mEtMP0a2BNxhcsii5r8j6OUh55zgC5VDZ/K1LhC1y42vKSt/jupESc
- provider: GitHub
  auth_token:
    secure: 0E2m/8I0e2mEtMP0a2BNxhcsii5r8j6OUh55zgC5VDZ/K1LhC1y42vKSt/jupESc